# Number of days of inactivity before an issue becomes stale
daysUntilStale: 60
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 15
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
# Label to use when marking an issue as stale
staleLabel: wontfix
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  Essa issue será posta em estado de espera caso não haja mais atividade nela.
  Muito obrigado pela compreensão e interesse pelo open Source!!
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
